const actions = {
	SET_AUTH_SESSION: 'SET_AUTH_SESSION',
	SET_AUTH_USER: 'SET_AUTH_USER',
	SET_AUTH_SIGNED_UP: 'SET_AUTH_SIGNED_UP',
	SET_AUTH_LOGGED_IN: 'SET_AUTH_LOGGED_IN',
	SET_AUTH_LOGGED_OUT: 'SET_AUTH_LOGGED_OUT',
};

export default actions;
